version: '3.9'

services:
  users-db:
    image: postgres:16
    container_name: users-db
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55433:5432"
    volumes:
      - users_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  accounts-db:
    image: postgres:16
    container_name: accounts-db
    environment:
      POSTGRES_DB: accountsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55434:5432"
    volumes:
      - accounts_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  credits-db:
    image: postgres:16
    container_name: credits-db
    environment:
      POSTGRES_DB: creditsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55435:5432"
    volumes:
      - credits_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  hangfire-db:
    image: postgres:16
    container_name: hangfire-db
    environment:
      POSTGRES_DB: hangfiredb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55436:5432"
    volumes:
      - hangfire_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
volumes:
  users_data:
  accounts_data:
  credits_data:
  hangfire_data: