// <auto-generated />
using System;
using CreditsService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CreditsService.Migrations
{
    [DbContext(typeof(CreditsDbContext))]
    [Migration("20260222164643_SeedCredits")]
    partial class SeedCredits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CreditsService.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("InitialAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastInterestApplicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RemainingAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TariffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("LastInterestApplicationDate");

                    b.HasIndex("TariffId");

                    b.HasIndex("UserId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd1"),
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InitialAmount = 120000m,
                            IsActive = true,
                            LastInterestApplicationDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RemainingAmount = 90000m,
                            TariffId = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc1"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd2"),
                            CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            InitialAmount = 300000m,
                            IsActive = true,
                            LastInterestApplicationDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            RemainingAmount = 240000m,
                            TariffId = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc3"),
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd3"),
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            InitialAmount = 80000m,
                            IsActive = true,
                            LastInterestApplicationDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RemainingAmount = 65000m,
                            TariffId = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc2"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd4"),
                            CreatedAt = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InitialAmount = 200000m,
                            IsActive = true,
                            LastInterestApplicationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RemainingAmount = 175000m,
                            TariffId = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc1"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd5"),
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            InitialAmount = 150000m,
                            IsActive = true,
                            LastInterestApplicationDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            RemainingAmount = 110000m,
                            TariffId = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc3"),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd6"),
                            CreatedAt = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            InitialAmount = 50000m,
                            IsActive = true,
                            LastInterestApplicationDate = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            RemainingAmount = 38000m,
                            TariffId = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc1"),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd7"),
                            CreatedAt = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            InitialAmount = 90000m,
                            IsActive = true,
                            LastInterestApplicationDate = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RemainingAmount = 72000m,
                            TariffId = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc2"),
                            UserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd8"),
                            CreatedAt = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            InitialAmount = 60000m,
                            IsActive = true,
                            LastInterestApplicationDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            RemainingAmount = 45000m,
                            TariffId = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc1"),
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd9"),
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InitialAmount = 400000m,
                            IsActive = true,
                            LastInterestApplicationDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RemainingAmount = 340000m,
                            TariffId = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc3"),
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd10"),
                            CreatedAt = new DateTime(2024, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            InitialAmount = 100000m,
                            IsActive = true,
                            LastInterestApplicationDate = new DateTime(2024, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            RemainingAmount = 85000m,
                            TariffId = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc2"),
                            UserId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd11"),
                            CreatedAt = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            InitialAmount = 220000m,
                            IsActive = true,
                            LastInterestApplicationDate = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            RemainingAmount = 190000m,
                            TariffId = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc3"),
                            UserId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd12"),
                            CreatedAt = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            InitialAmount = 70000m,
                            IsActive = true,
                            LastInterestApplicationDate = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            RemainingAmount = 52000m,
                            TariffId = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc1"),
                            UserId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd13"),
                            CreatedAt = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            InitialAmount = 130000m,
                            IsActive = true,
                            LastInterestApplicationDate = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            RemainingAmount = 100000m,
                            TariffId = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc2"),
                            UserId = new Guid("55555555-5555-5555-5555-555555555555")
                        });
                });

            modelBuilder.Entity("CreditsService.Entities.LoanOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OperationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.HasIndex("OperationDate");

                    b.ToTable("LoanOperations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee1"),
                            Amount = 10000m,
                            LoanId = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd1"),
                            OperationDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee2"),
                            Amount = 20000m,
                            LoanId = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd1"),
                            OperationDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee3"),
                            Amount = 25000m,
                            LoanId = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd2"),
                            OperationDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee4"),
                            Amount = 35000m,
                            LoanId = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd2"),
                            OperationDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee5"),
                            Amount = 15000m,
                            LoanId = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd3"),
                            OperationDate = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee6"),
                            Amount = 10000m,
                            LoanId = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd4"),
                            OperationDate = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee7"),
                            Amount = 15000m,
                            LoanId = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd4"),
                            OperationDate = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee8"),
                            Amount = 20000m,
                            LoanId = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd5"),
                            OperationDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee9"),
                            Amount = 20000m,
                            LoanId = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd5"),
                            OperationDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee10"),
                            Amount = 12000m,
                            LoanId = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd6"),
                            OperationDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee11"),
                            Amount = 8000m,
                            LoanId = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd7"),
                            OperationDate = new DateTime(2024, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee12"),
                            Amount = 10000m,
                            LoanId = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd7"),
                            OperationDate = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee13"),
                            Amount = 15000m,
                            LoanId = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd8"),
                            OperationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee14"),
                            Amount = 30000m,
                            LoanId = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd9"),
                            OperationDate = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee15"),
                            Amount = 30000m,
                            LoanId = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd9"),
                            OperationDate = new DateTime(2024, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee16"),
                            Amount = 15000m,
                            LoanId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd10"),
                            OperationDate = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee17"),
                            Amount = 10000m,
                            LoanId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd11"),
                            OperationDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee18"),
                            Amount = 20000m,
                            LoanId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd11"),
                            OperationDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee19"),
                            Amount = 8000m,
                            LoanId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd12"),
                            OperationDate = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee20"),
                            Amount = 10000m,
                            LoanId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd12"),
                            OperationDate = new DateTime(2024, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee21"),
                            Amount = 15000m,
                            LoanId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd13"),
                            OperationDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeee22"),
                            Amount = 15000m,
                            LoanId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddd13"),
                            OperationDate = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 2
                        });
                });

            modelBuilder.Entity("CreditsService.Entities.Tariff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("Tariffs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc1"),
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            InterestRate = 0.1490m,
                            IsActive = true,
                            Name = "Стандарт"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc2"),
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            InterestRate = 0.2190m,
                            IsActive = true,
                            Name = "Гибкий"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc3"),
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            InterestRate = 0.0990m,
                            IsActive = true,
                            Name = "Премиум"
                        });
                });

            modelBuilder.Entity("CreditsService.Entities.Loan", b =>
                {
                    b.HasOne("CreditsService.Entities.Tariff", "Tariff")
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("CreditsService.Entities.LoanOperation", b =>
                {
                    b.HasOne("CreditsService.Entities.Loan", "Loan")
                        .WithMany("Operations")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("CreditsService.Entities.Loan", b =>
                {
                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
